// SPDX-License-Identifier: MIT OR Apache-2.0
#include "test_paths.h"

#include "bitstream/bitstream.h"
#include "codestream_collect.h"
#include "image/image_internal.h"

#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#ifndef JXL_HEADER_FIELDS_INC
#define JXL_HEADER_FIELDS_INC "header_fields.inc"
#endif

static int read_file(const char *path, uint8_t **out, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        return -1;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return -1;
    }
    long sz = ftell(f);
    if (sz < 0) {
        fclose(f);
        return -1;
    }
    if (fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return -1;
    }
    uint8_t *buf = malloc((size_t)sz);
    if (buf == NULL) {
        fclose(f);
        return -1;
    }
    if (fread(buf, 1, (size_t)sz, f) != (size_t)sz) {
        free(buf);
        fclose(f);
        return -1;
    }
    fclose(f);
    *out = buf;
    *out_len = (size_t)sz;
    return 0;
}

static int process_one(const char *name, const char *update_path) {
    char path[1024];
    size_t file_len;
    jxl_allocator_state alloc;
    size_t cs_len;
    jxl_bs bs;
    jxl_parsed_image_header parsed;
    snprintf(path, sizeof(path), "%s/%s/input.jxl", JXL_OXIDE_FIXTURES_DIR, name);

    uint8_t *file = NULL;
    file_len = 0;
    if (read_file(path, &file, &file_len) != 0) {
        return -1;
    }

    jxl_allocator_init(&alloc, NULL);
    uint8_t *cs = NULL;
    cs_len = 0;
    if (jxl_collect_codestream(&alloc, file, file_len, &cs, &cs_len) != JXL_OK) {
        free(file);
        return -1;
    }
    free(file);

    jxl_bs_init(&bs, cs, cs_len);
    jxl_bs_status_t st = jxl_image_header_parse(&bs, &parsed);
    jxl_free(&alloc, cs);
    if (st != JXL_BS_OK) {
        fprintf(stderr, "%s: parse failed\n", name);
        return -1;
    }

    FILE *out = update_path != NULL ? fopen(update_path, "a") : stdout;
    if (out == NULL) {
        return -1;
    }
    fprintf(out, "    {\"%s\", %u, %u, %u, %u, %d},\n", name, parsed.size.width,
            parsed.size.height, parsed.bit_depth_bits, parsed.num_extra_channels,
            parsed.have_animation);
    if (update_path != NULL) {
        fclose(out);
    }
    return 0;
}

int main(void) {
    size_t i;
    const char *update_path = getenv("JXL_UPDATE_HEADER_GOLDEN");
    if (update_path == NULL) {
        update_path = JXL_HEADER_FIELDS_INC;
    }

    remove(update_path);
    FILE *hdr = fopen(update_path, "w");
    if (hdr == NULL) {
        return 1;
    }
    fprintf(hdr, "/* Generated by test_header_gen */\n");
    fprintf(hdr, "static const struct {\n");
    fprintf(hdr, "    const char *name;\n");
    fprintf(hdr, "    uint32_t width;\n");
    fprintf(hdr, "    uint32_t height;\n");
    fprintf(hdr, "    uint32_t bit_depth;\n");
    fprintf(hdr, "    uint32_t num_extra;\n");
    fprintf(hdr, "    int have_animation;\n");
    fprintf(hdr, "} k_header_fields[] = {\n");
    fclose(hdr);

    DIR *dir = opendir(JXL_OXIDE_FIXTURES_DIR);
    if (dir == NULL) {
        return 1;
    }

    char *names[64];
    size_t count = 0;
    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL && count < 64) {
        char path[1024];
        if (ent->d_name[0] == '.') {
            continue;
        }
        if (strcmp(ent->d_name, "benchmark-data") == 0 || strcmp(ent->d_name, "README.md") == 0) {
            continue;
        }
        snprintf(path, sizeof(path), "%s/%s/input.jxl", JXL_OXIDE_FIXTURES_DIR, ent->d_name);
        FILE *f = fopen(path, "rb");
        if (f == NULL) {
            continue;
        }
        fclose(f);
        names[count++] = strdup(ent->d_name);
    }
    closedir(dir);

    for (i = 0; i < count; ++i) {
        size_t j;
        for (j = i + 1; j < count; ++j) {
            if (strcmp(names[i], names[j]) > 0) {
                char *tmp = names[i];
                names[i] = names[j];
                names[j] = tmp;
            }
        }
    }

    int failed = 0;
    for (i = 0; i < count; ++i) {
        if (process_one(names[i], update_path) != 0) {
            failed = 1;
        }
        free(names[i]);
    }

    FILE *ftr = fopen(update_path, "a");
    if (ftr == NULL) {
        return 1;
    }
    fprintf(ftr, "};\n");
    fprintf(ftr, "static const size_t k_header_field_count =\n");
    fprintf(ftr, "    sizeof(k_header_fields) / sizeof(k_header_fields[0]);\n");
    fclose(ftr);

    return failed ? 1 : 0;
}
