// SPDX-License-Identifier: MIT OR Apache-2.0
#include "test_paths.h"

#include "collect_codestream.h"
#include "sha256.h"

#define _POSIX_C_SOURCE 200809L
#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


static int read_file(const char *path, uint8_t **out_data, size_t *out_len) {
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        return -1;
    }
    if (fseek(f, 0, SEEK_END) != 0) {
        fclose(f);
        return -1;
    }
    long size = ftell(f);
    if (size < 0) {
        fclose(f);
        return -1;
    }
    if (fseek(f, 0, SEEK_SET) != 0) {
        fclose(f);
        return -1;
    }
    uint8_t *data = malloc((size_t)size);
    if (data == NULL) {
        fclose(f);
        return -1;
    }
    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return -1;
    }
    fclose(f);
    *out_data = data;
    *out_len = (size_t)size;
    return 0;
}

static int process_fixture(const char *name, const char *update_path) {
    char path[1024];
    int n = snprintf(path, sizeof(path), "%s/%s/input.jxl", JXL_OXIDE_FIXTURES_DIR, name);
    size_t file_len;
    size_t cs_len;
    char digest[65];
    if (n < 0 || (size_t)n >= sizeof(path)) {
        return -1;
    }

    uint8_t *file_data = NULL;
    file_len = 0;
    if (read_file(path, &file_data, &file_len) != 0) {
        fprintf(stderr, "missing fixture %s\n", path);
        return -1;
    }

    uint8_t *codestream = NULL;
    cs_len = 0;
    jxl_bs_status_t st = jxl_test_extract_codestream(file_data, file_len, &codestream, &cs_len);
    free(file_data);
    if (st != JXL_BS_OK) {
        fprintf(stderr, "%s: extract failed: %s\n", name, jxl_bs_status_string(st));
        free(codestream);
        return -1;
    }

    jxl_test_sha256_hex(codestream, cs_len, digest);

    if (update_path != NULL) {
        FILE *out = fopen(update_path, "a");
        if (out == NULL) {
            free(codestream);
            return -1;
        }
        fprintf(out, "    {\"%s\", %zu, \"%s\"},\n", name, cs_len, digest);
        fclose(out);
    } else {
        printf("    {\"%s\", %zu, \"%s\"},\n", name, cs_len, digest);
    }

    free(codestream);
    return 0;
}

static int cmp_str(const void *a, const void *b) { return strcmp(*(const char *const *)a, *(const char *const *)b); }

int main(void) {
    size_t i;
    const char *update_path = getenv("JXL_UPDATE_CONTAINER_GOLDEN");
    if (update_path != NULL) {
        remove(update_path);
        FILE *out = fopen(update_path, "w");
        if (out == NULL) {
            return 1;
        }
        fprintf(out, "/* Generated by test_container_fixtures with JXL_UPDATE_CONTAINER_GOLDEN */\n");
        fprintf(out, "static const struct { const char *name; size_t len; const char *digest; } k_digests[] = {\n");
        fclose(out);
    }

    DIR *dir = opendir(JXL_OXIDE_FIXTURES_DIR);
    if (dir == NULL) {
        fprintf(stderr, "cannot open fixtures dir %s\n", JXL_OXIDE_FIXTURES_DIR);
        return 1;
    }

    char *names[64];
    size_t count = 0;
    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL && count < 64) {
        char path[1024];
        if (ent->d_name[0] == '.') {
            continue;
        }
        if (strcmp(ent->d_name, "benchmark-data") == 0 || strcmp(ent->d_name, "README.md") == 0) {
            continue;
        }
        snprintf(path, sizeof(path), "%s/%s/input.jxl", JXL_OXIDE_FIXTURES_DIR, ent->d_name);
        FILE *f = fopen(path, "rb");
        if (f == NULL) {
            continue;
        }
        fclose(f);
        names[count++] = strdup(ent->d_name);
    }
    closedir(dir);

    qsort(names, count, sizeof(char *), cmp_str);

    for (i = 0; i < count; ++i) {
        if (process_fixture(names[i], update_path) != 0) {
            size_t j;
            for (j = 0; j < count; ++j) {
                free(names[j]);
            }
            return 1;
        }
        free(names[i]);
    }

    if (update_path != NULL) {
        FILE *out = fopen(update_path, "a");
        if (out == NULL) {
            return 1;
        }
        fprintf(out, "};\n");
        fprintf(out, "static const size_t k_digest_count = sizeof(k_digests) / sizeof(k_digests[0]);\n");
        fclose(out);
        printf("updated %s\n", update_path);
        return 0;
    }

    printf("test_container_fixtures: printed %zu digests (set JXL_UPDATE_CONTAINER_GOLDEN to write header)\n",
           count);
    return 0;
}
