// SPDX-License-Identifier: MIT OR Apache-2.0
#ifndef JXL_JBR_ERROR_H_
#define JXL_JBR_ERROR_H_

typedef enum {
    JXL_JBR_OK = 0,
    JXL_JBR_NEED_MORE_DATA,
    JXL_JBR_BITSTREAM_ERROR,
    JXL_JBR_BROTLI_ERROR,
    JXL_JBR_INVALID_DATA,
    JXL_JBR_HUFFMAN_LOOKUP,
    JXL_JBR_WRITE_ERROR,
    JXL_JBR_UNAVAILABLE,
    JXL_JBR_DATA_INCOMPLETE,
    JXL_JBR_FRAME_INCOMPLETE,
    JXL_JBR_FRAME_PARSE,
    JXL_JBR_INCOMPATIBLE_FRAME,
    JXL_JBR_OUT_OF_MEMORY,
} jxl_jbr_status;

#endif /* JXL_JBR_ERROR_H_ */
