// SPDX-License-Identifier: MIT OR Apache-2.0
#ifndef JXL_MODULAR_ERROR_H_
#define JXL_MODULAR_ERROR_H_

typedef enum {
    JXL_MODULAR_OK = 0,
    JXL_MODULAR_INVALID_MA_TREE,
    JXL_MODULAR_GLOBAL_MA_TREE_NOT_AVAILABLE,
    JXL_MODULAR_INVALID_RCT_PARAMS,
    JXL_MODULAR_INVALID_PALETTE_PARAMS,
    JXL_MODULAR_INVALID_SQUEEZE_PARAMS,
    JXL_MODULAR_BITSTREAM_ERROR,
    JXL_MODULAR_DECODER_ERROR,
    JXL_MODULAR_OUT_OF_MEMORY,
} jxl_modular_status_t;

#endif /* JXL_MODULAR_ERROR_H_ */
