// SPDX-License-Identifier: MIT OR Apache-2.0
#ifndef JXL_CODING_ERROR_H_
#define JXL_CODING_ERROR_H_

typedef enum {
    JXL_CODING_OK = 0,
    JXL_CODING_EOF,
    JXL_CODING_BITSTREAM_ERROR,
    JXL_CODING_LZ77_NOT_ALLOWED,
    JXL_CODING_INVALID_ANS_HISTOGRAM,
    JXL_CODING_INVALID_ANS_STREAM,
    JXL_CODING_INVALID_INTEGER_CONFIG,
    JXL_CODING_INVALID_PERMUTATION,
    JXL_CODING_INVALID_PREFIX_HISTOGRAM,
    JXL_CODING_PREFIX_SYMBOL_TOO_LARGE,
    JXL_CODING_INVALID_CLUSTER,
    JXL_CODING_CLUSTER_HOLE,
    JXL_CODING_UNEXPECTED_LZ77_REPEAT,
    JXL_CODING_INVALID_LZ77_SYMBOL,
    JXL_CODING_OUT_OF_MEMORY,
} jxl_coding_status_t;

#endif /* JXL_CODING_ERROR_H_ */
